services:
  frontend:
    build: ./Frontend/my-app
    volumes:
      - ./Frontend/my-app:/frontend-dev
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    # depends_on:
    #   - backend
  # was das?????????????????
  #   stdin_open: true
  #   tty: true

  backend:
    build: ./Backend
    volumes:
      - ./Backend:/backend-dev
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  # was das?????????????????
  #   stdin_open: true
  #   tty: true