services:
  frontend:
    build: ./Frontend/my-app
    volumes:
      - ./Frontend/my-app:/frontend-dev
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    # depends_on:
    #   - backend
  # was das?????????????????
  #   stdin_open: true
  #   tty: true

  backend:
    build: ./Backend
    volumes:
      - ./Backend:/backend-dev
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - database
  # was das?????????????????
  #   stdin_open: true
  #   tty: true

  database:
  image: mysql:latest
  restart: unless-stopped
  environment:
    MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    MYSQL_DATABASE: calendar_app
  ports:
    - "3306:3306"
  networks:
    - "database"
  volumes:
    - Database:/etc/data
    - Database:/var/lib/mysql