# Generated by Django 5.0.4 on 2024-07-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_alter_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='endTime',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='startTime',
            new_name='start',
        ),
    ]
