# Generated by Django 5.0.4 on 2024-07-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0003_rename_endtime_event_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
    ]
